version: '3'
services:
  registory:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - 5000:5000
      - 5443:443
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/test.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/test.key
    volumes:
      - ./certs:/certs
      - ./auth:/auth
